### ISSUE TITLE
No spelling dictionaries, possibly a neovim issue

### ISSUE THREAD

**Issue by sethwoodworth** [dahu/vimple#12]
I get this error on load:

`Warning: Cannot find word list "en.utf-8.spl" or "en.ascii.spl" `

I remember hearing something about neovim not having spellcheck, or implementing spellcheck in a different way.

**Comment by dahu** [comment]
Can you show any more information about where and why you're getting this message?

Vimple does have a spelling assistant, but the code shouldn't run without you triggering it.

**Comment by sethwoodworth** [comment]
I think that your vim-asciidoc plugin is turning on spelling, which exposed a bug in neovim's spell checker.    I suppose I reported this bug to the wrong repo.
With this neovim [commit](https://github.com/neovim/neovim/commit/fd636fc6dcd8a547daab1544432877bf8efa0c1e), vimple and vim-asciidoc work with neovim.

**Comment by dahu** [comment]
Wonderful. Thanks for trying vim-asciidoc, and thanks for getting it to work on neovim.
